---
title: "Final Project"
author: "Jehan Joshi"
date: "8 July 2017"
output: html_document
---



###Company Description:- 

“Whether you shop from meticulously planned grocery lists or let whimsy guide your grazing, our unique food rituals define who we are. Instacart, a grocery ordering and delivery app, aims to make it easy to fill your refrigerator and pantry with your personal favorites and staples when you need them. After selecting products through the Instacart app, personal shoppers review your order and do the in-store shopping and delivery for you” – **Instacart** 

###Problem Statement:-

Predict which products will a user buy again for the first time or add to the cart during a separate session.

###Link:-

###[Kaggle](https://www.kaggle.com/c/instacart-market-basket-analysis)

###File Descriptions:-

##Aisles.CSV :- 

Contains a *unique Aisle id* and the description of the various aisles in a store.
Example :- [ 1, prepared soup salad ]. Where *aisle id* is one and prepared soup salad is the aisle description.

###Department.CSV :- 

This file contains the *department names* and their *unique id.* 

###Order_Products__*.csv :- 

These files specify which products were purchased in each order. *Order_Products__Prior.csv* contains previous order contents for all customers. *'Reordered'* indicates that the customer has a previous order that contains the product. 

###Note:-  

That some orders will have *no reordered items*. You may predict an explicit 'None' value for orders with no reordered items.

###Orders.csv :-  

This file tells to which set (prior, train, test) an order belongs. Prediction is for  reordered items only for the test set orders. *'order_dow'* is the day of week.

###Products.csv :- 

This file contains the  *product_id,product_name,aisle_id,department_id.*

###Methodologies To Be Considered:- 

* **Association rules for frequent itemsets.** 

* **Apriori Algorithm.** 

* **Colabrative filtering for making automatic predictions about the interests of a user by learning its preferences (or taste) based on information of his engagements with a set of available items.**

* **Clustering to group similar itemsets in a cluster.** 






